### ISSUE TITLE
Non-exhaustive matrix spread in CI

### ISSUE THREAD

**Issue by StoneCypher** [peggyjs/peggy#128]
Quoting @hildjj in [#109](https://github.com/peggyjs/peggy/pull/109#issuecomment-825871962)

> Running this on every version in the matrix seems like a waste, but it probably doesn't add as much time to the CI run as any of the ways to fix it that spring to mind.

This is pretty easy actually

You just spell out the non-sparse part of the range one by one

JSSM currently has a build policy of [win/mac/ubuntu] latest, plus (every ubuntu version back to 10), by example, with this (Taken from [jssm's gh build action](https://github.com/StoneCypher/jssm/blob/main/.github/workflows/nodejs.yml#L11-L28))

```
    strategy:
      matrix:
        include:
          - node-version: 16.x   # fastest, so run first, to error fast
            os: ubuntu-latest
          - node-version: 16.x   # slowest, so run next. sort by slowest from here to get earliest end through parallelism
            os: macos-latest
          - node-version: 16.x   # finish check big-3 on latest current
            os: windows-latest
          - node-version: 10.x  # lastly check just ubuntu on historic node versions because speed, oldest (slowest) first
            os: ubuntu-latest
          - node-version: 11.x
            os: ubuntu-latest
          - node-version: 12.x
            os: ubuntu-latest
          - node-version: 13.x
            os: ubuntu-latest
          - node-version: 14.x
            os: ubuntu-latest
          - node-version: 15.x
            os: ubuntu-latest

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
```

Let me know, if you want me to snap something like this in, what policy you want
